### ISSUE TITLE
eups remove failing

### ISSUE THREAD

**Issue by TallJimbo** [RobertLuptonTheGood/eups#111]
On all the packages I've tried running it on, `eups remove` fails with:
```
eups remove: '>' not supported between instances of 'Product' and 'Product'
```

Since `eups remove` is a relatively infrequently-used command, I suspect it's broken everywhere, but if anyone has trouble reproducing, I can work harder to figure out what's making my system special.

**Comment by TallJimbo** [comment]
Here's the full traceback from `--debug=raise` (as you can see this is eups 2.0.2).  Looks like this might occur on *any* topological dependency sort.
```
Traceback (most recent call last):
  File "/home/jbosch/LSST/sw/eups/2.0.2/bin/eups_impl.py", line 57, in <module>
    status = cmd.run() 
  File "/home/jbosch/LSST/sw/eups/2.0.2/python/eups/cmd.py", line 245, in run
    return self.execute()
  File "/home/jbosch/LSST/sw/eups/2.0.2/python/eups/cmd.py", line 172, in execute
    return ecmd.run()
  File "/home/jbosch/LSST/sw/eups/2.0.2/python/eups/cmd.py", line 245, in run
    return self.execute()
  File "/home/jbosch/LSST/sw/eups/2.0.2/python/eups/cmd.py", line 1496, in execute
    interactive=self.opts.interactive)
  File "/home/jbosch/LSST/sw/eups/2.0.2/python/eups/Eups.py", line 3201, in remove
    userInfo = self.uses(None)
  File "/home/jbosch/LSST/sw/eups/2.0.2/python/eups/Eups.py", line 3343, in uses
    deps = self.getDependentProducts(pi, shouldRaise=False, followExact=None, topological=True)
  File "/home/jbosch/LSST/sw/eups/2.0.2/python/eups/Eups.py", line 3143, in getDependentProducts
    checkCycles=checkCycles)] # products sorted topologically
  File "/home/jbosch/LSST/sw/eups/2.0.2/python/eups/Eups.py", line 3141, in <listcomp>
    sortedProducts = [t for t in
  File "/home/jbosch/LSST/sw/eups/2.0.2/python/eups/utils.py", line 862, in topologicalSort
    yield sorted(flattened_ordered, **cmp_or_key(cmp_prods_and_none))
  File "/home/jbosch/LSST/sw/eups/2.0.2/python/eups/utils.py", line 854, in cmp_prods_and_none
    return cmp(a, b)
  File "/home/jbosch/LSST/sw/eups/2.0.2/python/eups/utils.py", line 52, in cmp
    return (a > b) - (a < b)
TypeError: '>' not supported between instances of 'Product' and 'Product'
```

**Comment by TallJimbo** [comment]
So, that *particular* problem had already been fixed on master (it was a Python 3 compatibility issue, I think). I'm now seeing a different one.

**Comment by TallJimbo** [comment]
I've got a fix; closing in favor of a PR I'll create shortly.
