### ISSUE TITLE
Test failures on El Capitan runBashTest

### ISSUE THREAD

**Issue by timj** [RobertLuptonTheGood/eups#87]
Tests pass at commit c1f84a8 (merge of #82) but fail at current head (which is the merge of #85). I have tried with Python2.7 and Python3.4 on OS X El Capitan:
```
$ python3 tests/testAll.py 
...............................................................................................................FF
======================================================================
FAIL: testTapPackageDetectionEnvvar (testCommon.testEupspkg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/timj/work/eups/tests/testCommon.py", line 73, in runBashTest
    output = subprocess.check_output(testFn, stderr=subprocess.STDOUT)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '/Users/timj/work/eups/tests/testEupspkg/testTapPackageDetectionEnvvar.sh' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/timj/work/eups/tests/testCommon.py", line 91, in <lambda>
    class_members[methodName] = lambda self, testFn=testFn: runBashTest(self, testFn)
  File "/Users/timj/work/eups/tests/testCommon.py", line 75, in runBashTest
    self.fail(("Test %s failed (retcode=%s)\nscript: %s\noutput: " + "-"*65 + "\n%s" + "-"*73) % (testFn, e.returncode, testFn, e.output))
AssertionError: Test /Users/timj/work/eups/tests/testEupspkg/testTapPackageDetectionEnvvar.sh failed (retcode=1)
script: /Users/timj/work/eups/tests/testEupspkg/testTapPackageDetectionEnvvar.sh
output: -----------------------------------------------------------------
b'/Users/timj/work/eups/tests/testEupspkg/testTapPackageDetectionEnvvar.sh: line 4: /bin/setups.sh: No such file or directory\n'-------------------------------------------------------------------------

======================================================================
FAIL: testTapPackageDetectionFile (testCommon.testEupspkg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/timj/work/eups/tests/testCommon.py", line 73, in runBashTest
    output = subprocess.check_output(testFn, stderr=subprocess.STDOUT)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '/Users/timj/work/eups/tests/testEupspkg/testTapPackageDetectionFile.sh' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/timj/work/eups/tests/testCommon.py", line 91, in <lambda>
    class_members[methodName] = lambda self, testFn=testFn: runBashTest(self, testFn)
  File "/Users/timj/work/eups/tests/testCommon.py", line 75, in runBashTest
    self.fail(("Test %s failed (retcode=%s)\nscript: %s\noutput: " + "-"*65 + "\n%s" + "-"*73) % (testFn, e.returncode, testFn, e.output))
AssertionError: Test /Users/timj/work/eups/tests/testEupspkg/testTapPackageDetectionFile.sh failed (retcode=1)
script: /Users/timj/work/eups/tests/testEupspkg/testTapPackageDetectionFile.sh
output: -----------------------------------------------------------------
b'/Users/timj/work/eups/tests/testEupspkg/testTapPackageDetectionFile.sh: line 4: /bin/setups.sh: No such file or directory\n'-------------------------------------------------------------------------

----------------------------------------------------------------------
Ran 113 tests in 4.953s

FAILED (failures=2)

$ python2 tests/testAll.py 
...............................................................................................................FF
======================================================================
FAIL: testTapPackageDetectionEnvvar (testCommon.testEupspkg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/timj/work/eups/tests/testCommon.py", line 91, in <lambda>
    class_members[methodName] = lambda self, testFn=testFn: runBashTest(self, testFn)
  File "/Users/timj/work/eups/tests/testCommon.py", line 75, in runBashTest
    self.fail(("Test %s failed (retcode=%s)\nscript: %s\noutput: " + "-"*65 + "\n%s" + "-"*73) % (testFn, e.returncode, testFn, e.output))
AssertionError: Test /Users/timj/work/eups/tests/testEupspkg/testTapPackageDetectionEnvvar.sh failed (retcode=1)
script: /Users/timj/work/eups/tests/testEupspkg/testTapPackageDetectionEnvvar.sh
output: -----------------------------------------------------------------
/Users/timj/work/eups/tests/testEupspkg/testTapPackageDetectionEnvvar.sh: line 4: /bin/setups.sh: No such file or directory
-------------------------------------------------------------------------

======================================================================
FAIL: testTapPackageDetectionFile (testCommon.testEupspkg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/timj/work/eups/tests/testCommon.py", line 91, in <lambda>
    class_members[methodName] = lambda self, testFn=testFn: runBashTest(self, testFn)
  File "/Users/timj/work/eups/tests/testCommon.py", line 75, in runBashTest
    self.fail(("Test %s failed (retcode=%s)\nscript: %s\noutput: " + "-"*65 + "\n%s" + "-"*73) % (testFn, e.returncode, testFn, e.output))
AssertionError: Test /Users/timj/work/eups/tests/testEupspkg/testTapPackageDetectionFile.sh failed (retcode=1)
script: /Users/timj/work/eups/tests/testEupspkg/testTapPackageDetectionFile.sh
output: -----------------------------------------------------------------
/Users/timj/work/eups/tests/testEupspkg/testTapPackageDetectionFile.sh: line 4: /bin/setups.sh: No such file or directory
-------------------------------------------------------------------------

----------------------------------------------------------------------
Ran 113 tests in 4.724s

FAILED (failures=2)

```
Haven't had a chance to investigate yet but looks like a missing path prefix.

**Comment by timj** [comment]
Ok, two seconds later... All the other tests ensure that the EUPS environment is configured properly. The bash tests require that `$EUPS_DIR` is set externally.

**Comment by migueldvb** [comment]
All the tests are passing for me using python 3.5 and 2.7 on Linux.

**Comment by timj** [comment]
without setting `$EUPS_DIR` beforehand? They pass for me if I set that environment variable.

**Comment by mjuric** [comment]
I'll double-check it -- I thought the test framework set `$EUPS_DIR` itself, but that was probably incorrect.

**Comment by migueldvb** [comment]
@timj I have sourced `setups.sh` in my startup file so  $EUPS_DIR is set when I ran the tests. If $EUPS_DIR is not defined I see the first of those failures.

**Comment by mjuric** [comment]
@timj I'm confused -- how do you get into a state where you have the `PYTHONPATH` set correctly so it finds eups, but `EUPS_DIR` is not set? Are you setting them up manually? If I don't source `./bin/setups.sh`, I get errors like:
```
[mjuric@gallifrey (master) ~/projects/eups]$ (cd tests/; python testAll.py)
Traceback (most recent call last):
  File "testAll.py", line 24, in <module>
    tests += __import__(t).suite()
  File "/Users/mjuric/projects/eups/tests/testApp.py", line 11, in <module>
    from eups.utils import StringIO
ImportError: No module named 'eups'
```

**Comment by timj** [comment]
Thanks. Bad shell config. I've got too many shells open and I was running on one that had sourced a broken `setups.sh` but had a correct PYTHONPATH. (I was trying to fix the make/configure system to work with a space in the path). Tests do all run once I resourced the init script.
