### ISSUE TITLE
Python 2.6 compatibility broken

### ISSUE THREAD

**Issue by mjuric** [RobertLuptonTheGood/eups#89]
Here's what I get when I run the tests on `lsst-dev` (CentOS 6 machine):

```
[mjuric@lsst-dev [master] /ssd/mjuric/deleteme2/eups]$ (source bin/setups.sh; cd tests; python ./testAll.py)
..E...........E.....EEE..E.E..E.........E.EEE..EE...EE...E...........EE....E..EEE.......E...E.EEEE.......EEEEEEEE
======================================================================
ERROR: testDeclare (testCmd.CmdTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testCmd.py", line 254, in testDeclare
    self.assertIsNotNone(prod, msg="Failed to declare product")
AttributeError: 'CmdTestCase' object has no attribute 'assertIsNotNone'

======================================================================
ERROR: testRemove (testCmd.CmdTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testCmd.py", line 336, in testRemove
    self.assertIsNone(prod)
AttributeError: 'CmdTestCase' object has no attribute 'assertIsNone'

======================================================================
ERROR: testParsing (testDb.ChainFileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testDb.py", line 375, in testParsing
    self.assertIn("DarwinX86", flavors)
AttributeError: 'ChainFileTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testSetVersion (testDb.ChainFileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testDb.py", line 398, in testSetVersion
    self.assertIn("Linux", flavors)
AttributeError: 'ChainFileTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testWrite (testDb.ChainFileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testDb.py", line 459, in testWrite
    self.assertIn("DarwinX86", flavors)
AttributeError: 'ChainFileTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testFindFlavors (testDb.DatabaseTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testDb.py", line 517, in testFindFlavors
    self.assertIn(f, flavs)
AttributeError: 'DatabaseTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testFindProductNames (testDb.DatabaseTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testDb.py", line 500, in testFindProductNames
    self.assertIn(p, prods)
AttributeError: 'DatabaseTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testFindVersions (testDb.DatabaseTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testDb.py", line 510, in testFindVersions
    self.assertIn(v, vers)
AttributeError: 'DatabaseTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testAddFlavor (testDb.VersionFileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testDb.py", line 58, in testAddFlavor
    self.assertIn("Linux:rhel", flavors)
AttributeError: 'VersionFileTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testParsing (testDb.VersionFileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testDb.py", line 25, in testParsing
    self.assertIn("DarwinX86", flavors)
AttributeError: 'VersionFileTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testWrite (testDb.VersionFileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testDb.py", line 130, in testWrite
    self.assertIn("DarwinX86", flavors)
AttributeError: 'VersionFileTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testAssignTags (testEups.EupsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testEups.py", line 216, in testAssignTags
    self.assertIn("beta", prod.tags)
AttributeError: 'EupsTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testFindProduct (testEups.EupsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testEups.py", line 148, in testFindProduct
    self.assertIn("current", prod.tags)
AttributeError: 'EupsTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testInit (testEups.EupsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testEups.py", line 73, in testInit
    self.assertIn(testEupsStack, self.eups.versions)
AttributeError: 'EupsTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testSetup (testEups.EupsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testEups.py", line 472, in testSetup
    self.assertIn("PYTHON_DIR", os.environ)
AttributeError: 'EupsTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testUserTags (testEups.EupsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testEups.py", line 391, in testUserTags
    self.assertNotIn("user:mine", prod.tags, "user:mine already assigned")
AttributeError: 'EupsTestCase' object has no attribute 'assertNotIn'

======================================================================
ERROR: testInit (testProduct.ProductTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testProduct.py", line 36, in testInit
    self.assertIn("stable", p.tags)
AttributeError: 'ProductTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testAssignTag (testStack.ProductFamilyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testStack.py", line 59, in testAssignTag
    self.assertIn(tag, p.tags)
AttributeError: 'ProductFamilyTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testExport (testStack.ProductFamilyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testStack.py", line 90, in testExport
    self.assertIn("current", p.tags)
AttributeError: 'ProductFamilyTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testAddFlavor (testStack.ProductStackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testStack.py", line 279, in testAddFlavor
    self.assertIn(flav, flavors)
AttributeError: 'ProductStackTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testGetFlavors (testStack.ProductStackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testStack.py", line 261, in testGetFlavors
    self.assertIn(flav, flavors)
AttributeError: 'ProductStackTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testGetProductNames (testStack.ProductStackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testStack.py", line 152, in testGetProductNames
    self.assertIn(prod, prods)
AttributeError: 'ProductStackTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testGetVersions (testStack.ProductStackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testStack.py", line 178, in testGetVersions
    self.assertIn(ver, vers)
AttributeError: 'ProductStackTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testSaveEmptyFlavor (testStack.ProductStackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testStack.py", line 336, in testSaveEmptyFlavor
    self.assertIn(flav, flavors)
AttributeError: 'ProductStackTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testEmptyBlock (testTable.TableTestCase2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testTable.py", line 118, in testEmptyBlock
    self.assertIn("GOOBPATH", os.environ)
AttributeError: 'TableTestCase2' object has no attribute 'assertIn'

======================================================================
ERROR: testIfFlavor (testTable.TableTestCase2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testTable.py", line 72, in testIfFlavor
    self.assertIn("GOOBPATH", os.environ)
AttributeError: 'TableTestCase2' object has no attribute 'assertIn'

======================================================================
ERROR: testIfType (testTable.TableTestCase2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testTable.py", line 90, in testIfType
    self.assertIn("GOOBPATH", os.environ)
AttributeError: 'TableTestCase2' object has no attribute 'assertIn'

======================================================================
ERROR: testNoSetup (testTable.TableTestCase2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testTable.py", line 52, in testNoSetup
    self.assertIn("GOOBPATH", os.environ)
AttributeError: 'TableTestCase2' object has no attribute 'assertIn'

======================================================================
ERROR: testSetup (testTable.TableTestCase2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testTable.py", line 108, in testSetup
    self.assertIn("GOOBPATH", os.environ)
AttributeError: 'TableTestCase2' object has no attribute 'assertIn'

======================================================================
ERROR: testSaveLoad (testTags.TagsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testTags.py", line 107, in testSaveLoad
    self.assertIn(tag, names, tag+" not found amoung loaded names")
AttributeError: 'TagsTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testSaveLoadGlobalTags (testTags.TagsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testTags.py", line 150, in testSaveLoadGlobalTags
    self.assertIn(tag, names, tag+" not found amoung loaded names")
AttributeError: 'TagsTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testSaveLoadUserTags (testTags.TagsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testTags.py", line 131, in testSaveLoadUserTags
    self.assertIn(tag, names, tag+" not found amoung loaded names")
AttributeError: 'TagsTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testTagNames (testTags.TagsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testTags.py", line 40, in testTagNames
    self.assertIn("stable", tags)
AttributeError: 'TagsTestCase' object has no attribute 'assertIn'

======================================================================
ERROR: testDyldLibraryPathRetention_csh (testDyldLibraryPath.DyldLibraryPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testDyldLibraryPath.py", line 70, in testDyldLibraryPathRetention_csh
    self._run_script("/bin/csh", csh_test % 'a/b/c', "a/b/c\n/foo/bar:a/b/c\na/b/c\n")
  File "/ssd/mjuric/deleteme2/eups/tests/testDyldLibraryPath.py", line 58, in _run_script
    output = subprocess.check_output([shell, '-c', cmds], stderr=subprocess.STDOUT, env=self.env, universal_newlines=True)
AttributeError: 'module' object has no attribute 'check_output'

======================================================================
ERROR: testDyldLibraryPathRetention_sh (testDyldLibraryPath.DyldLibraryPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testDyldLibraryPath.py", line 65, in testDyldLibraryPathRetention_sh
    self._run_script("/bin/sh", sh_test % 'a/b/c', "a/b/c\n/foo/bar:a/b/c\na/b/c\n")
  File "/ssd/mjuric/deleteme2/eups/tests/testDyldLibraryPath.py", line 58, in _run_script
    output = subprocess.check_output([shell, '-c', cmds], stderr=subprocess.STDOUT, env=self.env, universal_newlines=True)
AttributeError: 'module' object has no attribute 'check_output'

======================================================================
ERROR: testTapPackageDetectionEnvvar (testCommon.testEupspkg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testCommon.py", line 91, in <lambda>
    class_members[methodName] = lambda self, testFn=testFn: runBashTest(self, testFn)
  File "/ssd/mjuric/deleteme2/eups/tests/testCommon.py", line 73, in runBashTest
    output = subprocess.check_output(testFn, stderr=subprocess.STDOUT)
AttributeError: 'module' object has no attribute 'check_output'

======================================================================
ERROR: testTapPackageDetectionFile (testCommon.testEupspkg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/mjuric/deleteme2/eups/tests/testCommon.py", line 91, in <lambda>
    class_members[methodName] = lambda self, testFn=testFn: runBashTest(self, testFn)
  File "/ssd/mjuric/deleteme2/eups/tests/testCommon.py", line 73, in runBashTest
    output = subprocess.check_output(testFn, stderr=subprocess.STDOUT)
AttributeError: 'module' object has no attribute 'check_output'

----------------------------------------------------------------------
Ran 113 tests in 2.509s

FAILED (errors=37)
```

**Comment by migueldvb** [comment]
The unittest AttributeErrors were introduced in  7e8c793605fc081da38f15789dab7a30a4ec0178. Sorry that I did not check the version number where those methods were added.

**Comment by mjuric** [comment]
No worries, it was an easy fix. I'll also add automated CI-ing against 2.6 once @RobertLuptonTheGood enables Travis.
